version: '3.8'

services:
  postgres_db:
    image: postgres:13
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: user_db
      POSTGRES_PASSWORD: user_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      retries: 5
      timeout: 5s

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/user_db
      SPRING_DATASOURCE_USERNAME: user_db
      SPRING_DATASOURCE_PASSWORD: user_db
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8083:8082"
    depends_on:
      postgres_db:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:





